steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/elastic-search-autocomplete/bestbuy-demo:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/elastic-search-autocomplete/bestbuy-demo:$REVISION_ID"
